version: '3.8'

services:
  lightrag:
    build: .
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage_upsert:/app/data/rag_storage_upsert
      - ./data/inputs:/app/data/inputs
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
